packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true
minimumReleaseAgeExclude:
  - ejs@3.1.10
  - semver@5.7.2
overrides:
  '@electron/get@>=3.0.0 <4.0.0': 3.1.0
  ejs@<3.1.10: ^3.1.10
  fast-uri@3.1.5: 3.1.6
  semver@>=2.0.0-alpha <5.7.2: ^5.7.2
